//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 12:19:36 PM CET 
//


package libis.user.pkg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the libis.user.pkg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Researcher_QNAME = new QName("", "researcher");
    private final static QName _User_QNAME = new QName("", "user");
    private final static QName _Users_QNAME = new QName("", "users");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: libis.user.pkg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Address.AddressTypes }
     * 
     */
    public Address.AddressTypes createAddressAddressTypes() {
        return new Address.AddressTypes();
    }

    /**
     * Create an instance of {@link Email }
     * 
     */
    public Email createEmail() {
        return new Email();
    }

    /**
     * Create an instance of {@link Email.EmailTypes }
     * 
     */
    public Email.EmailTypes createEmailEmailTypes() {
        return new Email.EmailTypes();
    }

    /**
     * Create an instance of {@link UserNote }
     * 
     */
    public UserNote createUserNote() {
        return new UserNote();
    }

    /**
     * Create an instance of {@link Parameter }
     * 
     */
    public Parameter createParameter() {
        return new Parameter();
    }

    /**
     * Create an instance of {@link RsLibrary }
     * 
     */
    public RsLibrary createRsLibrary() {
        return new RsLibrary();
    }

    /**
     * Create an instance of {@link UserRole }
     * 
     */
    public UserRole createUserRole() {
        return new UserRole();
    }

    /**
     * Create an instance of {@link UserBlock }
     * 
     */
    public UserBlock createUserBlock() {
        return new UserBlock();
    }

    /**
     * Create an instance of {@link Phone }
     * 
     */
    public Phone createPhone() {
        return new Phone();
    }

    /**
     * Create an instance of {@link Phone.PhoneTypes }
     * 
     */
    public Phone.PhoneTypes createPhonePhoneTypes() {
        return new Phone.PhoneTypes();
    }

    /**
     * Create an instance of {@link LibraryNotice }
     * 
     */
    public LibraryNotice createLibraryNotice() {
        return new LibraryNotice();
    }

    /**
     * Create an instance of {@link UserStatistic }
     * 
     */
    public UserStatistic createUserStatistic() {
        return new UserStatistic();
    }

    /**
     * Create an instance of {@link UserIdentifier }
     * 
     */
    public UserIdentifier createUserIdentifier() {
        return new UserIdentifier();
    }

    /**
     * Create an instance of {@link User }
     * 
     */
    public User createUser() {
        return new User();
    }

    /**
     * Create an instance of {@link Researcher }
     * 
     */
    public Researcher createResearcher() {
        return new Researcher();
    }

    /**
     * Create an instance of {@link Users }
     * 
     */
    public Users createUsers() {
        return new Users();
    }

    /**
     * Create an instance of {@link ResearcherPreviousExternalOrganizationAffiliations }
     * 
     */
    public ResearcherPreviousExternalOrganizationAffiliations createResearcherPreviousExternalOrganizationAffiliations() {
        return new ResearcherPreviousExternalOrganizationAffiliations();
    }

    /**
     * Create an instance of {@link ResearcherDescription }
     * 
     */
    public ResearcherDescription createResearcherDescription() {
        return new ResearcherDescription();
    }

    /**
     * Create an instance of {@link ResearcherLanguage }
     * 
     */
    public ResearcherLanguage createResearcherLanguage() {
        return new ResearcherLanguage();
    }

    /**
     * Create an instance of {@link Addresses }
     * 
     */
    public Addresses createAddresses() {
        return new Addresses();
    }

    /**
     * Create an instance of {@link ResearcherKeywords }
     * 
     */
    public ResearcherKeywords createResearcherKeywords() {
        return new ResearcherKeywords();
    }

    /**
     * Create an instance of {@link UserRoles }
     * 
     */
    public UserRoles createUserRoles() {
        return new UserRoles();
    }

    /**
     * Create an instance of {@link ProxyForUser }
     * 
     */
    public ProxyForUser createProxyForUser() {
        return new ProxyForUser();
    }

    /**
     * Create an instance of {@link RsLibraries }
     * 
     */
    public RsLibraries createRsLibraries() {
        return new RsLibraries();
    }

    /**
     * Create an instance of {@link ResearcherAssociation }
     * 
     */
    public ResearcherAssociation createResearcherAssociation() {
        return new ResearcherAssociation();
    }

    /**
     * Create an instance of {@link ResearcherPreviousOrganizationAffiliations }
     * 
     */
    public ResearcherPreviousOrganizationAffiliations createResearcherPreviousOrganizationAffiliations() {
        return new ResearcherPreviousOrganizationAffiliations();
    }

    /**
     * Create an instance of {@link ResearcherEducation }
     * 
     */
    public ResearcherEducation createResearcherEducation() {
        return new ResearcherEducation();
    }

    /**
     * Create an instance of {@link ResearcherDescriptions }
     * 
     */
    public ResearcherDescriptions createResearcherDescriptions() {
        return new ResearcherDescriptions();
    }

    /**
     * Create an instance of {@link ResearcherEducations }
     * 
     */
    public ResearcherEducations createResearcherEducations() {
        return new ResearcherEducations();
    }

    /**
     * Create an instance of {@link ResearcherWebpage }
     * 
     */
    public ResearcherWebpage createResearcherWebpage() {
        return new ResearcherWebpage();
    }

    /**
     * Create an instance of {@link ResearcherHonors }
     * 
     */
    public ResearcherHonors createResearcherHonors() {
        return new ResearcherHonors();
    }

    /**
     * Create an instance of {@link ResearcherWebpages }
     * 
     */
    public ResearcherWebpages createResearcherWebpages() {
        return new ResearcherWebpages();
    }

    /**
     * Create an instance of {@link ResearcherKeyword }
     * 
     */
    public ResearcherKeyword createResearcherKeyword() {
        return new ResearcherKeyword();
    }

    /**
     * Create an instance of {@link ResearcherAlternateEmails }
     * 
     */
    public ResearcherAlternateEmails createResearcherAlternateEmails() {
        return new ResearcherAlternateEmails();
    }

    /**
     * Create an instance of {@link ResearcherResearchTopics }
     * 
     */
    public ResearcherResearchTopics createResearcherResearchTopics() {
        return new ResearcherResearchTopics();
    }

    /**
     * Create an instance of {@link ResearcherExternalOrganizationAffiliations }
     * 
     */
    public ResearcherExternalOrganizationAffiliations createResearcherExternalOrganizationAffiliations() {
        return new ResearcherExternalOrganizationAffiliations();
    }

    /**
     * Create an instance of {@link Parameters }
     * 
     */
    public Parameters createParameters() {
        return new Parameters();
    }

    /**
     * Create an instance of {@link ResearcherAssociations }
     * 
     */
    public ResearcherAssociations createResearcherAssociations() {
        return new ResearcherAssociations();
    }

    /**
     * Create an instance of {@link UserNotes }
     * 
     */
    public UserNotes createUserNotes() {
        return new UserNotes();
    }

    /**
     * Create an instance of {@link Phones }
     * 
     */
    public Phones createPhones() {
        return new Phones();
    }

    /**
     * Create an instance of {@link ContactInfo }
     * 
     */
    public ContactInfo createContactInfo() {
        return new ContactInfo();
    }

    /**
     * Create an instance of {@link Emails }
     * 
     */
    public Emails createEmails() {
        return new Emails();
    }

    /**
     * Create an instance of {@link ResearcherLanguages }
     * 
     */
    public ResearcherLanguages createResearcherLanguages() {
        return new ResearcherLanguages();
    }

    /**
     * Create an instance of {@link ResearcherAlternateEmail }
     * 
     */
    public ResearcherAlternateEmail createResearcherAlternateEmail() {
        return new ResearcherAlternateEmail();
    }

    /**
     * Create an instance of {@link ProxyForUsers }
     * 
     */
    public ProxyForUsers createProxyForUsers() {
        return new ProxyForUsers();
    }

    /**
     * Create an instance of {@link UserBlocks }
     * 
     */
    public UserBlocks createUserBlocks() {
        return new UserBlocks();
    }

    /**
     * Create an instance of {@link UserStatistics }
     * 
     */
    public UserStatistics createUserStatistics() {
        return new UserStatistics();
    }

    /**
     * Create an instance of {@link ResearcherHonor }
     * 
     */
    public ResearcherHonor createResearcherHonor() {
        return new ResearcherHonor();
    }

    /**
     * Create an instance of {@link LibraryNotices }
     * 
     */
    public LibraryNotices createLibraryNotices() {
        return new LibraryNotices();
    }

    /**
     * Create an instance of {@link ResearcherNameVariant }
     * 
     */
    public ResearcherNameVariant createResearcherNameVariant() {
        return new ResearcherNameVariant();
    }

    /**
     * Create an instance of {@link ResearcherNameVariants }
     * 
     */
    public ResearcherNameVariants createResearcherNameVariants() {
        return new ResearcherNameVariants();
    }

    /**
     * Create an instance of {@link ResearcherOrganizationAffiliations }
     * 
     */
    public ResearcherOrganizationAffiliations createResearcherOrganizationAffiliations() {
        return new ResearcherOrganizationAffiliations();
    }

    /**
     * Create an instance of {@link ResearcherOrganizationAffiliation }
     * 
     */
    public ResearcherOrganizationAffiliation createResearcherOrganizationAffiliation() {
        return new ResearcherOrganizationAffiliation();
    }

    /**
     * Create an instance of {@link ResearcherResearchTopic }
     * 
     */
    public ResearcherResearchTopic createResearcherResearchTopic() {
        return new ResearcherResearchTopic();
    }

    /**
     * Create an instance of {@link UserIdentifiers }
     * 
     */
    public UserIdentifiers createUserIdentifiers() {
        return new UserIdentifiers();
    }

    /**
     * Create an instance of {@link Address.Country }
     * 
     */
    public Address.Country createAddressCountry() {
        return new Address.Country();
    }

    /**
     * Create an instance of {@link Address.AddressTypes.AddressType }
     * 
     */
    public Address.AddressTypes.AddressType createAddressAddressTypesAddressType() {
        return new Address.AddressTypes.AddressType();
    }

    /**
     * Create an instance of {@link Email.EmailTypes.EmailType }
     * 
     */
    public Email.EmailTypes.EmailType createEmailEmailTypesEmailType() {
        return new Email.EmailTypes.EmailType();
    }

    /**
     * Create an instance of {@link UserNote.NoteType }
     * 
     */
    public UserNote.NoteType createUserNoteNoteType() {
        return new UserNote.NoteType();
    }

    /**
     * Create an instance of {@link Parameter.Type }
     * 
     */
    public Parameter.Type createParameterType() {
        return new Parameter.Type();
    }

    /**
     * Create an instance of {@link Parameter.Value }
     * 
     */
    public Parameter.Value createParameterValue() {
        return new Parameter.Value();
    }

    /**
     * Create an instance of {@link RsLibrary.Code }
     * 
     */
    public RsLibrary.Code createRsLibraryCode() {
        return new RsLibrary.Code();
    }

    /**
     * Create an instance of {@link UserRole.Status }
     * 
     */
    public UserRole.Status createUserRoleStatus() {
        return new UserRole.Status();
    }

    /**
     * Create an instance of {@link UserRole.Scope }
     * 
     */
    public UserRole.Scope createUserRoleScope() {
        return new UserRole.Scope();
    }

    /**
     * Create an instance of {@link UserRole.RoleType }
     * 
     */
    public UserRole.RoleType createUserRoleRoleType() {
        return new UserRole.RoleType();
    }

    /**
     * Create an instance of {@link UserBlock.BlockType }
     * 
     */
    public UserBlock.BlockType createUserBlockBlockType() {
        return new UserBlock.BlockType();
    }

    /**
     * Create an instance of {@link UserBlock.BlockDescription }
     * 
     */
    public UserBlock.BlockDescription createUserBlockBlockDescription() {
        return new UserBlock.BlockDescription();
    }

    /**
     * Create an instance of {@link Phone.PhoneTypes.PhoneType }
     * 
     */
    public Phone.PhoneTypes.PhoneType createPhonePhoneTypesPhoneType() {
        return new Phone.PhoneTypes.PhoneType();
    }

    /**
     * Create an instance of {@link LibraryNotice.Code }
     * 
     */
    public LibraryNotice.Code createLibraryNoticeCode() {
        return new LibraryNotice.Code();
    }

    /**
     * Create an instance of {@link UserStatistic.StatisticCategory }
     * 
     */
    public UserStatistic.StatisticCategory createUserStatisticStatisticCategory() {
        return new UserStatistic.StatisticCategory();
    }

    /**
     * Create an instance of {@link UserStatistic.CategoryType }
     * 
     */
    public UserStatistic.CategoryType createUserStatisticCategoryType() {
        return new UserStatistic.CategoryType();
    }

    /**
     * Create an instance of {@link UserIdentifier.IdType }
     * 
     */
    public UserIdentifier.IdType createUserIdentifierIdType() {
        return new UserIdentifier.IdType();
    }

    /**
     * Create an instance of {@link User.RecordType }
     * 
     */
    public User.RecordType createUserRecordType() {
        return new User.RecordType();
    }

    /**
     * Create an instance of {@link User.UserTitle }
     * 
     */
    public User.UserTitle createUserUserTitle() {
        return new User.UserTitle();
    }

    /**
     * Create an instance of {@link User.JobCategory }
     * 
     */
    public User.JobCategory createUserJobCategory() {
        return new User.JobCategory();
    }

    /**
     * Create an instance of {@link User.Gender }
     * 
     */
    public User.Gender createUserGender() {
        return new User.Gender();
    }

    /**
     * Create an instance of {@link User.UserGroup }
     * 
     */
    public User.UserGroup createUserUserGroup() {
        return new User.UserGroup();
    }

    /**
     * Create an instance of {@link User.CampusCode }
     * 
     */
    public User.CampusCode createUserCampusCode() {
        return new User.CampusCode();
    }

    /**
     * Create an instance of {@link User.CatalogerLevel }
     * 
     */
    public User.CatalogerLevel createUserCatalogerLevel() {
        return new User.CatalogerLevel();
    }

    /**
     * Create an instance of {@link User.PreferredLanguage }
     * 
     */
    public User.PreferredLanguage createUserPreferredLanguage() {
        return new User.PreferredLanguage();
    }

    /**
     * Create an instance of {@link User.AccountType }
     * 
     */
    public User.AccountType createUserAccountType() {
        return new User.AccountType();
    }

    /**
     * Create an instance of {@link User.Status }
     * 
     */
    public User.Status createUserStatus() {
        return new User.Status();
    }

    /**
     * Create an instance of {@link User.Requests }
     * 
     */
    public User.Requests createUserRequests() {
        return new User.Requests();
    }

    /**
     * Create an instance of {@link User.Loans }
     * 
     */
    public User.Loans createUserLoans() {
        return new User.Loans();
    }

    /**
     * Create an instance of {@link User.Fees }
     * 
     */
    public User.Fees createUserFees() {
        return new User.Fees();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Researcher }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "researcher")
    public JAXBElement<Researcher> createResearcher(Researcher value) {
        return new JAXBElement<Researcher>(_Researcher_QNAME, Researcher.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link User }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "user")
    public JAXBElement<User> createUser(User value) {
        return new JAXBElement<User>(_User_QNAME, User.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Users }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "users")
    public JAXBElement<Users> createUsers(Users value) {
        return new JAXBElement<Users>(_Users_QNAME, Users.class, null, value);
    }

}
