//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.02.04 at 12:19:36 PM CET 
//


package libis.user.pkg;

import java.io.StringWriter;
import java.util.HashMap;

import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;




/**
 * User Object.
 * 
 * <p>Java class for user complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="user">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="record_type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="primary_id" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="first_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="middle_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="last_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="full_name" type="{}string600Length" minOccurs="0"/>
 *         &lt;element name="pin_number" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="user_title" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="job_category" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="job_description" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="gender" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="user_group" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="campus_code" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string50Length">
 *                 &lt;attribute name="desc" type="{}string255Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="web_site_url" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="cataloger_level" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="preferred_language" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="birth_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="expiry_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="purge_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="account_type" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="external_id" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="password" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="force_password_change" type="{}string4Length" minOccurs="0"/>
 *         &lt;element name="status" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;>string255Length">
 *                 &lt;attribute name="desc" type="{}string4000Length" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="status_date" type="{http://www.w3.org/2001/XMLSchema}date" minOccurs="0"/>
 *         &lt;element name="requests" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="loans" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="fees" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="contact_info" type="{}contact_info" minOccurs="0"/>
 *         &lt;element name="user_identifiers" type="{}user_identifiers" minOccurs="0"/>
 *         &lt;element name="user_roles" type="{}user_roles" minOccurs="0"/>
 *         &lt;element name="user_blocks" type="{}user_blocks" minOccurs="0"/>
 *         &lt;element name="user_notes" type="{}user_notes" minOccurs="0"/>
 *         &lt;element name="user_statistics" type="{}user_statistics" minOccurs="0"/>
 *         &lt;element name="proxy_for_users" type="{}proxy_for_users" minOccurs="0"/>
 *         &lt;element name="rs_libraries" type="{}rs_libraries" minOccurs="0"/>
 *         &lt;element name="library_notices" type="{}library_notices" minOccurs="0"/>
 *         &lt;element name="source_link_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="source_institution_code" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="linking_id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="pref_first_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="pref_middle_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="pref_last_name" type="{}string255Length" minOccurs="0"/>
 *         &lt;element name="is_researcher" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="researcher" type="{}researcher" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "user", propOrder = {

})
@XmlRootElement(name = "user")
public class User {
	private static final Logger LOGGER = LogManager.getLogger(User.class);
    @XmlElement(name = "record_type")
    protected User.RecordType recordType;
    @XmlElement(name = "primary_id")
    protected String primaryId;
    @XmlElement(name = "first_name")
    protected String firstName;
    @XmlElement(name = "middle_name")
    protected String middleName;
    @XmlElement(name = "last_name")
    protected String lastName;
    @XmlElement(name = "full_name")
    protected String fullName;
    @XmlElement(name = "pin_number")
    protected String pinNumber;
    @XmlElement(name = "user_title")
    protected User.UserTitle userTitle;
    @XmlElement(name = "job_category")
    protected User.JobCategory jobCategory;
    @XmlElement(name = "job_description")
    protected String jobDescription;
    protected User.Gender gender;
    @XmlElement(name = "user_group")
    protected User.UserGroup userGroup;
    @XmlElement(name = "campus_code")
    protected User.CampusCode campusCode;
    @XmlElement(name = "web_site_url")
    protected String webSiteUrl;
    @XmlElement(name = "cataloger_level")
    protected User.CatalogerLevel catalogerLevel;
    @XmlElement(name = "preferred_language")
    protected User.PreferredLanguage preferredLanguage;
    @XmlElement(name = "birth_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar birthDate;
    @XmlElement(name = "expiry_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar expiryDate;
    @XmlElement(name = "purge_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar purgeDate;
    @XmlElement(name = "account_type")
    protected User.AccountType accountType;
    @XmlElement(name = "external_id")
    protected String externalId;
    protected String password;
    @XmlElement(name = "force_password_change")
    protected String forcePasswordChange;
    protected User.Status status;
    @XmlElement(name = "status_date")
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar statusDate;
    protected User.Requests requests;
    protected User.Loans loans;
    protected User.Fees fees;
    @XmlElement(name = "contact_info")
    protected ContactInfo contactInfo;
    @XmlElement(name = "user_identifiers")
    protected UserIdentifiers userIdentifiers;
    @XmlElement(name = "user_roles")
    protected UserRoles userRoles;
    @XmlElement(name = "user_blocks")
    protected UserBlocks userBlocks;
    @XmlElement(name = "user_notes")
    protected UserNotes userNotes;
    @XmlElement(name = "user_statistics")
    protected UserStatistics userStatistics;
    @XmlElement(name = "proxy_for_users")
    protected ProxyForUsers proxyForUsers;
    @XmlElement(name = "rs_libraries")
    protected RsLibraries rsLibraries;
    @XmlElement(name = "library_notices")
    protected LibraryNotices libraryNotices;
    @XmlElement(name = "source_link_id")
    protected String sourceLinkId;
    @XmlElement(name = "source_institution_code")
    protected String sourceInstitutionCode;
    @XmlElement(name = "linking_id")
    protected String linkingId;
    @XmlElement(name = "pref_first_name")
    protected String prefFirstName;
    @XmlElement(name = "pref_middle_name")
    protected String prefMiddleName;
    @XmlElement(name = "pref_last_name")
    protected String prefLastName;
    @XmlElement(name = "is_researcher")
    protected Boolean isResearcher;
    protected Researcher researcher;
    @XmlAttribute(name = "link")
    protected String link;

	public void updUser(User fromU) {
		this.setLastName(fromU.getLastName());
		this.setFirstName(fromU.getFirstName());
		this.setExpiryDate(fromU.getExpiryDate());
		this.setCampusCode(fromU.getCampusCode());
		this.setUserGroup(fromU.getUserGroup());
		this.setContactInfo(fromU.getContactInfo());
	}    

	public static String getUserGroupByDesc(String institution, String userGroupDesc) throws Exception {
		HashMap<String, String> USER_GROUPS = new HashMap<String, String>();
	    boolean foundDesc = false;
	    String desc = "";
		switch (institution) {
			case "ECB":
			case "ECB_SB":
			    USER_GROUPS.put("01","Permanent staff");
			    USER_GROUPS.put("02","Temporary staff A");
			    USER_GROUPS.put("14","Temporary staff B");
			    USER_GROUPS.put("03","Library staff");
			    USER_GROUPS.put("04","Executive Board");
			    USER_GROUPS.put("05","Directors");
			    USER_GROUPS.put("06","Managers");
			    USER_GROUPS.put("07","Temporary leaver A");
			    USER_GROUPS.put("08","Temporary leaver B");
			    USER_GROUPS.put("09","Temporary leaver C");
			    USER_GROUPS.put("10","Temporary leaver D");
			    USER_GROUPS.put("11","Seconded staff A");
			    USER_GROUPS.put("12","Seconded staff B");
			    USER_GROUPS.put("13","External staff");
			    USER_GROUPS.put("90","Routing");
			    USER_GROUPS.put("95","Bookbinder");    
				break;
			default:
				throw new Exception("error at getUserGroupByDesc : no usergroupcodes defined for "+institution);			
		}

		for (HashMap.Entry<String, String> set : USER_GROUPS.entrySet()) {
			if (set.getValue().equals(userGroupDesc)) {
				foundDesc = true;
				desc = set.getKey();
			}
		}
		if (foundDesc == false)  {
			throw new Exception("error at getUserGroupByDesc : could not find code for "+userGroupDesc);
		}
		return(desc);
}	    
    
    
	public static String getCampusCodeByDesc(String institution, String campusCodeDesc) throws Exception {
		HashMap<String, String> CAMPUS_CODES = new HashMap<String, String>();
	    boolean foundDesc = false;
	    String desc = "";
		switch (institution) {
			case "ECB":
			case "ECB_SB":
			    CAMPUS_CODES.put("001","EB");
			    CAMPUS_CODES.put("002","SB");
			    CAMPUS_CODES.put("003","CSO");
			    CAMPUS_CODES.put("005","BN");
			    CAMPUS_CODES.put("006","C");
			    CAMPUS_CODES.put("007","E");
			    CAMPUS_CODES.put("008","ESRB");
			    CAMPUS_CODES.put("010","HR");
			    CAMPUS_CODES.put("011","IS");
			    CAMPUS_CODES.put("012","IA");
			    CAMPUS_CODES.put("013","I");
			    CAMPUS_CODES.put("014","L");
			    CAMPUS_CODES.put("015","MF");
			    CAMPUS_CODES.put("016","MIP");
			    CAMPUS_CODES.put("017","M");
			    /* obsolete 20201013
			     * CAMPUS_CODES.put("018","MS1");
			     * CAMPUS_CODES.put("019","MS2");
			     * CAMPUS_CODES.put("020","MS3");
			     * CAMPUS_CODES.put("021","MS4");
			     * CAMPUS_CODES.put("025","DSSB");
			     * */
			    CAMPUS_CODES.put("022","R");
			    CAMPUS_CODES.put("023","RM");
			    CAMPUS_CODES.put("024","SE");
			    CAMPUS_CODES.put("026","S");
			    CAMPUS_CODES.put("027","T2SP");
			    CAMPUS_CODES.put("028","MP");
			    CAMPUS_CODES.put("029","CS");
			    CAMPUS_CODES.put("030","CEB");
			    CAMPUS_CODES.put("031","HOL");
			    CAMPUS_CODES.put("032","OMI");
			    CAMPUS_CODES.put("033","SGO");
			    CAMPUS_CODES.put("034","SIB");
			    CAMPUS_CODES.put("035","SPL");
			    CAMPUS_CODES.put("036","SSR");
			    CAMPUS_CODES.put("037","UDI");
			    CAMPUS_CODES.put("038","N/A");
				break;
			default:
				throw new Exception("error at getCampusCodeByDesc : no campuscodes defined for "+institution);			
		}

		for (HashMap.Entry<String, String> set : CAMPUS_CODES.entrySet()) {
			if (set.getValue().equals(campusCodeDesc)) {
				foundDesc = true;
				desc = set.getKey();
			}
		}
		if (foundDesc == false)  {
			throw new Exception("error at getCampusCodeByDesc : could not find code for "+campusCodeDesc);
		}
		return(desc);
}	    
    
    public static void jaxbObjectToXML(User u)
    {
        try
        {
            //Create JAXB Context
            JAXBContext jaxbContext = JAXBContext.newInstance(User.class);
             
            //Create Marshaller
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
 
            //Required formatting??
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
 
            //Print XML String to Console
            StringWriter sw = new StringWriter();
             
            //Write XML to StringWriter
            jaxbMarshaller.marshal(u, sw);
             
            //Verify XML Content
            String xmlContent = sw.toString();
            LOGGER.info(xmlContent);
 
        } catch (JAXBException e) {
            e.printStackTrace();
        }
    }    
    
    /**
     * Gets the value of the recordType property.
     * 
     * @return
     *     possible object is
     *     {@link User.RecordType }
     *     
     */
    public User.RecordType getRecordType() {
        return recordType;
    }

    /**
     * Sets the value of the recordType property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.RecordType }
     *     
     */
    public void setRecordType(User.RecordType value) {
        this.recordType = value;
    }

    /**
     * Gets the value of the primaryId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimaryId() {
        return primaryId;
    }

    /**
     * Sets the value of the primaryId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimaryId(String value) {
        this.primaryId = value;
    }

    /**
     * Gets the value of the firstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFirstName() {
        return firstName;
    }

    /**
     * Sets the value of the firstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFirstName(String value) {
        this.firstName = value;
    }

    /**
     * Gets the value of the middleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMiddleName() {
        return middleName;
    }

    /**
     * Sets the value of the middleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMiddleName(String value) {
        this.middleName = value;
    }

    /**
     * Gets the value of the lastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLastName() {
        return lastName;
    }

    /**
     * Sets the value of the lastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLastName(String value) {
        this.lastName = value;
    }

    /**
     * Gets the value of the fullName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFullName() {
        return fullName;
    }

    /**
     * Sets the value of the fullName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFullName(String value) {
        this.fullName = value;
    }

    /**
     * Gets the value of the pinNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPinNumber() {
        return pinNumber;
    }

    /**
     * Sets the value of the pinNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPinNumber(String value) {
        this.pinNumber = value;
    }

    /**
     * Gets the value of the userTitle property.
     * 
     * @return
     *     possible object is
     *     {@link User.UserTitle }
     *     
     */
    public User.UserTitle getUserTitle() {
        return userTitle;
    }

    /**
     * Sets the value of the userTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.UserTitle }
     *     
     */
    public void setUserTitle(User.UserTitle value) {
        this.userTitle = value;
    }

    /**
     * Gets the value of the jobCategory property.
     * 
     * @return
     *     possible object is
     *     {@link User.JobCategory }
     *     
     */
    public User.JobCategory getJobCategory() {
        return jobCategory;
    }

    /**
     * Sets the value of the jobCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.JobCategory }
     *     
     */
    public void setJobCategory(User.JobCategory value) {
        this.jobCategory = value;
    }

    /**
     * Gets the value of the jobDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJobDescription() {
        return jobDescription;
    }

    /**
     * Sets the value of the jobDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJobDescription(String value) {
        this.jobDescription = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link User.Gender }
     *     
     */
    public User.Gender getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Gender }
     *     
     */
    public void setGender(User.Gender value) {
        this.gender = value;
    }

    /**
     * Gets the value of the userGroup property.
     * 
     * @return
     *     possible object is
     *     {@link User.UserGroup }
     *     
     */
    public User.UserGroup getUserGroup() {
        return userGroup;
    }

    /**
     * Sets the value of the userGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.UserGroup }
     *     
     */
    public void setUserGroup(User.UserGroup value) {
        this.userGroup = value;
    }

    /**
     * Gets the value of the campusCode property.
     * 
     * @return
     *     possible object is
     *     {@link User.CampusCode }
     *     
     */
    public User.CampusCode getCampusCode() {
        return campusCode;
    }

    /**
     * Sets the value of the campusCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.CampusCode }
     *     
     */
    public void setCampusCode(User.CampusCode value) {
        this.campusCode = value;
    }

    /**
     * Gets the value of the webSiteUrl property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getWebSiteUrl() {
        return webSiteUrl;
    }

    /**
     * Sets the value of the webSiteUrl property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setWebSiteUrl(String value) {
        this.webSiteUrl = value;
    }

    /**
     * Gets the value of the catalogerLevel property.
     * 
     * @return
     *     possible object is
     *     {@link User.CatalogerLevel }
     *     
     */
    public User.CatalogerLevel getCatalogerLevel() {
        return catalogerLevel;
    }

    /**
     * Sets the value of the catalogerLevel property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.CatalogerLevel }
     *     
     */
    public void setCatalogerLevel(User.CatalogerLevel value) {
        this.catalogerLevel = value;
    }

    /**
     * Gets the value of the preferredLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link User.PreferredLanguage }
     *     
     */
    public User.PreferredLanguage getPreferredLanguage() {
        return preferredLanguage;
    }

    /**
     * Sets the value of the preferredLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.PreferredLanguage }
     *     
     */
    public void setPreferredLanguage(User.PreferredLanguage value) {
        this.preferredLanguage = value;
    }

    /**
     * Gets the value of the birthDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getBirthDate() {
        return birthDate;
    }

    /**
     * Sets the value of the birthDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setBirthDate(XMLGregorianCalendar value) {
        this.birthDate = value;
    }

    /**
     * Gets the value of the expiryDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getExpiryDate() {
        return expiryDate;
    }

    /**
     * Sets the value of the expiryDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setExpiryDate(XMLGregorianCalendar value) {
        this.expiryDate = value;
    }

    /**
     * Gets the value of the purgeDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getPurgeDate() {
        return purgeDate;
    }

    /**
     * Sets the value of the purgeDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setPurgeDate(XMLGregorianCalendar value) {
        this.purgeDate = value;
    }

    /**
     * Gets the value of the accountType property.
     * 
     * @return
     *     possible object is
     *     {@link User.AccountType }
     *     
     */
    public User.AccountType getAccountType() {
        return accountType;
    }

    /**
     * Sets the value of the accountType property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.AccountType }
     *     
     */
    public void setAccountType(User.AccountType value) {
        this.accountType = value;
    }

    /**
     * Gets the value of the externalId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExternalId() {
        return externalId;
    }

    /**
     * Sets the value of the externalId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExternalId(String value) {
        this.externalId = value;
    }

    /**
     * Gets the value of the password property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPassword() {
        return password;
    }

    /**
     * Sets the value of the password property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPassword(String value) {
        this.password = value;
    }

    /**
     * Gets the value of the forcePasswordChange property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getForcePasswordChange() {
        return forcePasswordChange;
    }

    /**
     * Sets the value of the forcePasswordChange property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setForcePasswordChange(String value) {
        this.forcePasswordChange = value;
    }

    /**
     * Gets the value of the status property.
     * 
     * @return
     *     possible object is
     *     {@link User.Status }
     *     
     */
    public User.Status getStatus() {
        return status;
    }

    /**
     * Sets the value of the status property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Status }
     *     
     */
    public void setStatus(User.Status value) {
        this.status = value;
    }

    /**
     * Gets the value of the statusDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getStatusDate() {
        return statusDate;
    }

    /**
     * Sets the value of the statusDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setStatusDate(XMLGregorianCalendar value) {
        this.statusDate = value;
    }

    /**
     * Gets the value of the requests property.
     * 
     * @return
     *     possible object is
     *     {@link User.Requests }
     *     
     */
    public User.Requests getRequests() {
        return requests;
    }

    /**
     * Sets the value of the requests property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Requests }
     *     
     */
    public void setRequests(User.Requests value) {
        this.requests = value;
    }

    /**
     * Gets the value of the loans property.
     * 
     * @return
     *     possible object is
     *     {@link User.Loans }
     *     
     */
    public User.Loans getLoans() {
        return loans;
    }

    /**
     * Sets the value of the loans property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Loans }
     *     
     */
    public void setLoans(User.Loans value) {
        this.loans = value;
    }

    /**
     * Gets the value of the fees property.
     * 
     * @return
     *     possible object is
     *     {@link User.Fees }
     *     
     */
    public User.Fees getFees() {
        return fees;
    }

    /**
     * Sets the value of the fees property.
     * 
     * @param value
     *     allowed object is
     *     {@link User.Fees }
     *     
     */
    public void setFees(User.Fees value) {
        this.fees = value;
    }

    /**
     * Gets the value of the contactInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ContactInfo }
     *     
     */
    public ContactInfo getContactInfo() {
        return contactInfo;
    }

    /**
     * Sets the value of the contactInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactInfo }
     *     
     */
    public void setContactInfo(ContactInfo value) {
        this.contactInfo = value;
    }

    /**
     * Gets the value of the userIdentifiers property.
     * 
     * @return
     *     possible object is
     *     {@link UserIdentifiers }
     *     
     */
    public UserIdentifiers getUserIdentifiers() {
        return userIdentifiers;
    }

    /**
     * Sets the value of the userIdentifiers property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserIdentifiers }
     *     
     */
    public void setUserIdentifiers(UserIdentifiers value) {
        this.userIdentifiers = value;
    }

    /**
     * Gets the value of the userRoles property.
     * 
     * @return
     *     possible object is
     *     {@link UserRoles }
     *     
     */
    public UserRoles getUserRoles() {
        return userRoles;
    }

    /**
     * Sets the value of the userRoles property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserRoles }
     *     
     */
    public void setUserRoles(UserRoles value) {
        this.userRoles = value;
    }

    /**
     * Gets the value of the userBlocks property.
     * 
     * @return
     *     possible object is
     *     {@link UserBlocks }
     *     
     */
    public UserBlocks getUserBlocks() {
        return userBlocks;
    }

    /**
     * Sets the value of the userBlocks property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserBlocks }
     *     
     */
    public void setUserBlocks(UserBlocks value) {
        this.userBlocks = value;
    }

    /**
     * Gets the value of the userNotes property.
     * 
     * @return
     *     possible object is
     *     {@link UserNotes }
     *     
     */
    public UserNotes getUserNotes() {
        return userNotes;
    }

    /**
     * Sets the value of the userNotes property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserNotes }
     *     
     */
    public void setUserNotes(UserNotes value) {
        this.userNotes = value;
    }

    /**
     * Gets the value of the userStatistics property.
     * 
     * @return
     *     possible object is
     *     {@link UserStatistics }
     *     
     */
    public UserStatistics getUserStatistics() {
        return userStatistics;
    }

    /**
     * Sets the value of the userStatistics property.
     * 
     * @param value
     *     allowed object is
     *     {@link UserStatistics }
     *     
     */
    public void setUserStatistics(UserStatistics value) {
        this.userStatistics = value;
    }

    /**
     * Gets the value of the proxyForUsers property.
     * 
     * @return
     *     possible object is
     *     {@link ProxyForUsers }
     *     
     */
    public ProxyForUsers getProxyForUsers() {
        return proxyForUsers;
    }

    /**
     * Sets the value of the proxyForUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link ProxyForUsers }
     *     
     */
    public void setProxyForUsers(ProxyForUsers value) {
        this.proxyForUsers = value;
    }

    /**
     * Gets the value of the rsLibraries property.
     * 
     * @return
     *     possible object is
     *     {@link RsLibraries }
     *     
     */
    public RsLibraries getRsLibraries() {
        return rsLibraries;
    }

    /**
     * Sets the value of the rsLibraries property.
     * 
     * @param value
     *     allowed object is
     *     {@link RsLibraries }
     *     
     */
    public void setRsLibraries(RsLibraries value) {
        this.rsLibraries = value;
    }

    /**
     * Gets the value of the libraryNotices property.
     * 
     * @return
     *     possible object is
     *     {@link LibraryNotices }
     *     
     */
    public LibraryNotices getLibraryNotices() {
        return libraryNotices;
    }

    /**
     * Sets the value of the libraryNotices property.
     * 
     * @param value
     *     allowed object is
     *     {@link LibraryNotices }
     *     
     */
    public void setLibraryNotices(LibraryNotices value) {
        this.libraryNotices = value;
    }

    /**
     * Gets the value of the sourceLinkId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceLinkId() {
        return sourceLinkId;
    }

    /**
     * Sets the value of the sourceLinkId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceLinkId(String value) {
        this.sourceLinkId = value;
    }

    /**
     * Gets the value of the sourceInstitutionCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSourceInstitutionCode() {
        return sourceInstitutionCode;
    }

    /**
     * Sets the value of the sourceInstitutionCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSourceInstitutionCode(String value) {
        this.sourceInstitutionCode = value;
    }

    /**
     * Gets the value of the linkingId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLinkingId() {
        return linkingId;
    }

    /**
     * Sets the value of the linkingId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLinkingId(String value) {
        this.linkingId = value;
    }

    /**
     * Gets the value of the prefFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefFirstName() {
        return prefFirstName;
    }

    /**
     * Sets the value of the prefFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefFirstName(String value) {
        this.prefFirstName = value;
    }

    /**
     * Gets the value of the prefMiddleName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefMiddleName() {
        return prefMiddleName;
    }

    /**
     * Sets the value of the prefMiddleName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefMiddleName(String value) {
        this.prefMiddleName = value;
    }

    /**
     * Gets the value of the prefLastName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrefLastName() {
        return prefLastName;
    }

    /**
     * Sets the value of the prefLastName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrefLastName(String value) {
        this.prefLastName = value;
    }

    /**
     * Gets the value of the isResearcher property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isIsResearcher() {
        return isResearcher;
    }

    /**
     * Sets the value of the isResearcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setIsResearcher(Boolean value) {
        this.isResearcher = value;
    }

    /**
     * Gets the value of the researcher property.
     * 
     * @return
     *     possible object is
     *     {@link Researcher }
     *     
     */
    public Researcher getResearcher() {
        return researcher;
    }

    /**
     * Sets the value of the researcher property.
     * 
     * @param value
     *     allowed object is
     *     {@link Researcher }
     *     
     */
    public void setResearcher(Researcher value) {
        this.researcher = value;
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class AccountType {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string50Length">
     *       &lt;attribute name="desc" type="{}string255Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CampusCode {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CatalogerLevel {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>float">
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Fees {

        @XmlValue
        protected float value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         */
        public float getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(float value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Gender {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class JobCategory {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Loans {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PreferredLanguage {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class RecordType {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Requests {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Status {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class UserGroup {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;>string255Length">
     *       &lt;attribute name="desc" type="{}string4000Length" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class UserTitle {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }

}
