//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.22 at 08:56:09 AM CET 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://com/exlibris/urm/general/xmlbeans", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package libis.alma.api.rest;
