//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.15 at 09:36:17 AM CET 
//


package libis.invoice.pkg;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * List of exchange rates between the invoice currency and foreign currencies.
 * Relevant only if the institution has ledgers in more than one currency.
 * 
 * <p>Java class for explicit_ratios complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="explicit_ratios">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="explicit_ratio" type="{}explicit_ratio" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "explicit_ratios", propOrder = {
    "explicitRatio"
})
public class ExplicitRatios {

    @XmlElement(name = "explicit_ratio", required = true)
    protected List<ExplicitRatio> explicitRatio;

    /**
     * Gets the value of the explicitRatio property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the explicitRatio property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getExplicitRatio().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ExplicitRatio }
     * 
     * 
     */
    public List<ExplicitRatio> getExplicitRatio() {
        if (explicitRatio == null) {
            explicitRatio = new ArrayList<ExplicitRatio>();
        }
        return this.explicitRatio;
    }

}
