//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.15 at 09:36:17 AM CET 
//


package libis.invoice.pkg;

import java.util.ArrayList;
import java.util.List;
import java.io.StringWriter;
import java.math.BigDecimal;


import javax.xml.bind.JAXBContext;
import javax.xml.bind.JAXBException;
import javax.xml.bind.Marshaller;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementWrapper;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.datatype.XMLGregorianCalendar;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;

import libis.alma.api.rest.AlmaDate;


/**
 * Invoice Object.
 * 
 * <p>Java class for invoice complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="invoice">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="number" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="invoice_date" type="{http://www.w3.org/2001/XMLSchema}date"/>
 *         &lt;element name="total_amount" type="{http://www.w3.org/2001/XMLSchema}decimal"/>
 *         &lt;element name="total_invoice_lines_amount" type="{http://www.w3.org/2001/XMLSchema}decimal" minOccurs="0"/>
 *         &lt;element name="currency" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vendor">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vendor_account" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="vendor_contact_person" type="{}contact_person" minOccurs="0"/>
 *         &lt;element name="payment_method" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="reference_number" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="creation_form" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="owner">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="invoice_status" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="invoice_workflow_status" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="invoice_approval_status" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="approved_by" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="additional_charges" type="{}additional_charges" minOccurs="0"/>
 *         &lt;element name="invoice_vat" type="{}invoice_vat" minOccurs="0"/>
 *         &lt;element name="explicit_ratios" type="{}explicit_ratios" minOccurs="0"/>
 *         &lt;element name="payment" type="{}payment" minOccurs="0"/>
 *         &lt;element name="alerts" type="{}alerts" minOccurs="0"/>
 *         &lt;element name="notes" type="{}notes" minOccurs="0"/>
 *         &lt;element name="number_of_lines" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
 *                 &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="invoice_line" type="{}invoice_line" minOccurs="0"/>
 *       &lt;/all>
 *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "invoice", propOrder = {

})

@XmlRootElement(name = "invoice")
public class Invoice {
	private static final Logger LOGGER = LogManager.getLogger(Invoice.class);
    protected String id;
    @XmlElement(required = true)
    protected String number;
    @XmlElement(name = "invoice_date", required = true)
    @XmlSchemaType(name = "date")
    protected XMLGregorianCalendar invoiceDate;
    @XmlElement(name = "total_amount", required = true)
    protected BigDecimal totalAmount;
    @XmlElement(name = "total_invoice_lines_amount")
    protected BigDecimal totalInvoiceLinesAmount;
    protected Invoice.Currency currency;
    @XmlElement(required = true)
    protected Invoice.Vendor vendor;
    @XmlElement(name = "vendor_account")
    protected String vendorAccount;
    @XmlElement(name = "vendor_contact_person")
    protected ContactPerson vendorContactPerson;
    @XmlElement(name = "payment_method")
    protected Invoice.PaymentMethod paymentMethod;
    @XmlElement(name = "reference_number")
    protected String referenceNumber;
    @XmlElement(name = "creation_form")
    protected Invoice.CreationForm creationForm;
    @XmlElement(required = true)
    protected Invoice.Owner owner;
    @XmlElement(name = "invoice_status")
    protected Invoice.InvoiceStatus invoiceStatus;
    @XmlElement(name = "invoice_workflow_status")
    protected Invoice.InvoiceWorkflowStatus invoiceWorkflowStatus;
    @XmlElement(name = "invoice_approval_status")
    protected Invoice.InvoiceApprovalStatus invoiceApprovalStatus;
    @XmlElement(name = "approved_by")
    protected String approvedBy;
    @XmlElement(name = "additional_charges")
    protected AdditionalCharges additionalCharges;
    @XmlElement(name = "invoice_vat")
    protected InvoiceVat invoiceVat;
    @XmlElement(name = "explicit_ratios")
    protected ExplicitRatios explicitRatios;
    protected Payment payment;
    protected Alerts alerts;
    protected Notes notes;
    @XmlElement(name = "number_of_lines")
    protected Invoice.NumberOfLines numberOfLines;
    //@XmlElement(name = "invoice_lines")
    @XmlElementWrapper(name="invoice_lines")
    @XmlElement(name="invoice_line")    
    protected List<InvoiceLine> invoiceLines;
    @XmlAttribute(name = "link")
    protected String link;
    
    public static double VATCodeToPercentage (String VATCode) {
    	double retPct;
    	switch (VATCode) {
			case "DE":    			
			case "EE":
    		case "OE":
			case "RE": 
     		case "VE":
    				retPct = 21.0d;
    				break;
    		case "CB":
    		case "DB":
    		case "EB":
    		case "QB":
    		case "VB":
    				retPct = 6.0d;
    				break;
    		case "VA":    				
       		case "WA":
       				retPct = 0.0d;
       				break;
    		default:
    				retPct = 21.0d;
    				break;
    	}
    	return(retPct);
    }
    
    public Invoice copyWithoutInvoiceLines(Invoice i) {
    	try {
    		Invoice iOut = new Invoice();
    		iOut.setAdditionalCharges(i.getAdditionalCharges());
    		iOut.setAlerts(i.getAlerts());
    		iOut.setApprovedBy(i.getApprovedBy());
    		iOut.setCreationForm(i.getCreationForm());
    		iOut.setCurrency(i.getCurrency());
    		iOut.setExplicitRatios(i.getExplicitRatios());
    		iOut.setId(i.getId());
    		iOut.setInvoiceApprovalStatus(i.getInvoiceApprovalStatus());
    		iOut.setInvoiceDate(i.getInvoiceDate());
    		iOut.setInvoiceStatus(i.getInvoiceStatus());
    		iOut.setInvoiceVat(i.getInvoiceVat());
    		iOut.setInvoiceWorkflowStatus(i.getInvoiceWorkflowStatus());
    		iOut.setLink(i.getLink());
    		iOut.setNotes(i.getNotes());
    		iOut.setNumber(i.getNumber());
    		iOut.setOwner(i.getOwner());
    		iOut.setPayment(i.getPayment());
    		iOut.setPaymentMethod(i.getPaymentMethod());
    		iOut.setReferenceNumber(i.getReferenceNumber());
    		iOut.setTotalAmount(i.getTotalAmount());
    		iOut.setTotalInvoiceLinesAmount(i.getTotalInvoiceLinesAmount());
    		iOut.setVendor(i.getVendor());
    		iOut.setVendorAccount(i.getVendorAccount());
    		iOut.setVendorContactPerson(i.getVendorContactPerson());
    		//without invoicelines
    		Invoice.NumberOfLines nol = new Invoice.NumberOfLines();
    		nol.setValue(0);
    		iOut.setNumberOfLines(nol);
    		iOut.setInvoiceLines(null);
    		return(iOut);
    	} catch (Exception e) {
    		return(i);
    	}
    }

    public static void jaxbObjectToXML(Invoice i)
    {
        try
        {
            //Create JAXB Context
            JAXBContext jaxbContext = JAXBContext.newInstance(Invoice.class);
             
            //Create Marshaller
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
 
            //Required formatting??
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
 
            //Print XML String to Console
            StringWriter sw = new StringWriter();
             
            //Write XML to StringWriter
            jaxbMarshaller.marshal(i, sw);
             
            //Verify XML Content
            String xmlContent = sw.toString();
            LOGGER.info(xmlContent);
 
        } catch (JAXBException e) {
            e.printStackTrace();
        }
    }
    
    public Invoice () {
    	//empty constructor
    	this.invoiceLines = new ArrayList<InvoiceLine>();
    }

    public static Invoice testInvoice() {
    	Invoice invoice = new Invoice();
    	invoice.setInvoiceLines(null);
    	Invoice.Currency ic = new Invoice.Currency();
    	ic.setValue("EUR");
    	invoice.setCurrency(ic);
    	invoice.setNumber("54444445");
    	invoice.setApprovedBy("Pieter");
    	Invoice.PaymentMethod ip = new Invoice.PaymentMethod();
    	ip.setValue("ACCOUNTINGDEPARTMENT");
    	invoice.setPaymentMethod(ip);
    	InvoiceVat iv = new InvoiceVat();
    	iv.setPercentage(new BigDecimal(21.0d));
    	iv.setVatPerInvoiceLine(false);
    	iv.setExpendedFromFund(false);
    	InvoiceVat.Type ivt = new InvoiceVat.Type();
    	ivt.setValue("INCLUSIVE");
    	iv.setType(ivt);
    	invoice.setInvoiceVat(iv);
    	/*Invoice.Owner iown = new Invoice.Owner();
    	iown.setValue("SBIB");
    	invoice.setOwner(iown);*/
    	Invoice.Vendor vendor = new Invoice.Vendor();
    	vendor.setValue("4410000045");
    	vendor.setDesc("TestWithVendor");
    	invoice.setTotalAmount(new BigDecimal(100d));
    	invoice.setVendor(vendor);
    	invoice.setInvoiceDate(AlmaDate.currentDate());
    	invoice.invoiceLines = new ArrayList<InvoiceLine> ();
    	InvoiceLine invoiceLine = new InvoiceLine();
    	invoiceLine.setId("100");
    	invoiceLine.setNote("Eerste invoiceLine");
    	invoiceLine.setPoLine("POL-123456");
    	invoiceLine.setPrice(new BigDecimal(100d));
    	invoiceLine.setAdditionalInfo("TestLine");
    	invoice.addInvoiceLine(invoiceLine);
    	return(invoice);
    }

    public String invXML() {
        try
        {
            //Create JAXB Context
            JAXBContext jaxbContext = JAXBContext.newInstance(Invoice.class);
             
            //Create Marshaller
            Marshaller jaxbMarshaller = jaxbContext.createMarshaller();
 
            //Required formatting??
            jaxbMarshaller.setProperty(Marshaller.JAXB_FORMATTED_OUTPUT, Boolean.TRUE);
 
            //Print XML String to Console
            StringWriter sw = new StringWriter();
             
            //Write XML to StringWriter
            jaxbMarshaller.marshal(this, sw);
             
            //Verify XML Content
            String xmlContent = sw.toString();
            return(xmlContent);
 
        } catch (JAXBException e) {
            return(e.getMessage());
        }
    }
    
    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }

    /**
     * Gets the value of the number property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNumber() {
        return number;
    }

    /**
     * Sets the value of the number property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNumber(String value) {
        this.number = value;
    }

    /**
     * Gets the value of the invoiceDate property.
     * 
     * @return
     *     possible object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public XMLGregorianCalendar getInvoiceDate() {
        return invoiceDate;
    }

    /**
     * Sets the value of the invoiceDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link XMLGregorianCalendar }
     *     
     */
    public void setInvoiceDate(XMLGregorianCalendar value) {
        this.invoiceDate = value;
    }

    /**
     * Gets the value of the totalAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalAmount() {
        return totalAmount;
    }

    /**
     * Sets the value of the totalAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalAmount(BigDecimal value) {
        this.totalAmount = value;
    }

    /**
     * Gets the value of the totalInvoiceLinesAmount property.
     * 
     * @return
     *     possible object is
     *     {@link BigDecimal }
     *     
     */
    public BigDecimal getTotalInvoiceLinesAmount() {
        return totalInvoiceLinesAmount;
    }

    /**
     * Sets the value of the totalInvoiceLinesAmount property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigDecimal }
     *     
     */
    public void setTotalInvoiceLinesAmount(BigDecimal value) {
        this.totalInvoiceLinesAmount = value;
    }

    /**
     * Gets the value of the currency property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.Currency }
     *     
     */
    public Invoice.Currency getCurrency() {
        return currency;
    }

    /**
     * Sets the value of the currency property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.Currency }
     *     
     */
    public void setCurrency(Invoice.Currency value) {
        this.currency = value;
    }

    /**
     * Gets the value of the vendor property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.Vendor }
     *     
     */
    public Invoice.Vendor getVendor() {
        return vendor;
    }

    /**
     * Sets the value of the vendor property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.Vendor }
     *     
     */
    public void setVendor(Invoice.Vendor value) {
        this.vendor = value;
    }

    /**
     * Gets the value of the vendorAccount property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVendorAccount() {
        return vendorAccount;
    }

    /**
     * Sets the value of the vendorAccount property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVendorAccount(String value) {
        this.vendorAccount = value;
    }

    /**
     * Gets the value of the vendorContactPerson property.
     * 
     * @return
     *     possible object is
     *     {@link ContactPerson }
     *     
     */
    public ContactPerson getVendorContactPerson() {
        return vendorContactPerson;
    }

    /**
     * Sets the value of the vendorContactPerson property.
     * 
     * @param value
     *     allowed object is
     *     {@link ContactPerson }
     *     
     */
    public void setVendorContactPerson(ContactPerson value) {
        this.vendorContactPerson = value;
    }

    /**
     * Gets the value of the paymentMethod property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.PaymentMethod }
     *     
     */
    public Invoice.PaymentMethod getPaymentMethod() {
        return paymentMethod;
    }

    /**
     * Sets the value of the paymentMethod property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.PaymentMethod }
     *     
     */
    public void setPaymentMethod(Invoice.PaymentMethod value) {
        this.paymentMethod = value;
    }

    /**
     * Gets the value of the referenceNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReferenceNumber() {
        return referenceNumber;
    }

    /**
     * Sets the value of the referenceNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReferenceNumber(String value) {
        this.referenceNumber = value;
    }

    /**
     * Gets the value of the creationForm property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.CreationForm }
     *     
     */
    public Invoice.CreationForm getCreationForm() {
        return creationForm;
    }

    /**
     * Sets the value of the creationForm property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.CreationForm }
     *     
     */
    public void setCreationForm(Invoice.CreationForm value) {
        this.creationForm = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.Owner }
     *     
     */
    public Invoice.Owner getOwner() {
        return owner;
    }

    /**
     * Sets the value of the owner property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.Owner }
     *     
     */
    public void setOwner(Invoice.Owner value) {
        this.owner = value;
    }

    /**
     * Gets the value of the invoiceStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.InvoiceStatus }
     *     
     */
    public Invoice.InvoiceStatus getInvoiceStatus() {
        return invoiceStatus;
    }

    /**
     * Sets the value of the invoiceStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.InvoiceStatus }
     *     
     */
    public void setInvoiceStatus(Invoice.InvoiceStatus value) {
        this.invoiceStatus = value;
    }

    /**
     * Gets the value of the invoiceWorkflowStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.InvoiceWorkflowStatus }
     *     
     */
    public Invoice.InvoiceWorkflowStatus getInvoiceWorkflowStatus() {
        return invoiceWorkflowStatus;
    }

    /**
     * Sets the value of the invoiceWorkflowStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.InvoiceWorkflowStatus }
     *     
     */
    public void setInvoiceWorkflowStatus(Invoice.InvoiceWorkflowStatus value) {
        this.invoiceWorkflowStatus = value;
    }

    /**
     * Gets the value of the invoiceApprovalStatus property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.InvoiceApprovalStatus }
     *     
     */
    public Invoice.InvoiceApprovalStatus getInvoiceApprovalStatus() {
        return invoiceApprovalStatus;
    }

    /**
     * Sets the value of the invoiceApprovalStatus property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.InvoiceApprovalStatus }
     *     
     */
    public void setInvoiceApprovalStatus(Invoice.InvoiceApprovalStatus value) {
        this.invoiceApprovalStatus = value;
    }

    /**
     * Gets the value of the approvedBy property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getApprovedBy() {
        return approvedBy;
    }

    /**
     * Sets the value of the approvedBy property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setApprovedBy(String value) {
        this.approvedBy = value;
    }

    /**
     * Gets the value of the additionalCharges property.
     * 
     * @return
     *     possible object is
     *     {@link AdditionalCharges }
     *     
     */
    public AdditionalCharges getAdditionalCharges() {
        return additionalCharges;
    }

    /**
     * Sets the value of the additionalCharges property.
     * 
     * @param value
     *     allowed object is
     *     {@link AdditionalCharges }
     *     
     */
    public void setAdditionalCharges(AdditionalCharges value) {
        this.additionalCharges = value;
    }

    /**
     * Gets the value of the invoiceVat property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceVat }
     *     
     */
    public InvoiceVat getInvoiceVat() {
        return invoiceVat;
    }

    /**
     * Sets the value of the invoiceVat property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceVat }
     *     
     */
    public void setInvoiceVat(InvoiceVat value) {
        this.invoiceVat = value;
    }

    /**
     * Gets the value of the explicitRatios property.
     * 
     * @return
     *     possible object is
     *     {@link ExplicitRatios }
     *     
     */
    public ExplicitRatios getExplicitRatios() {
        return explicitRatios;
    }

    /**
     * Sets the value of the explicitRatios property.
     * 
     * @param value
     *     allowed object is
     *     {@link ExplicitRatios }
     *     
     */
    public void setExplicitRatios(ExplicitRatios value) {
        this.explicitRatios = value;
    }

    /**
     * Gets the value of the payment property.
     * 
     * @return
     *     possible object is
     *     {@link Payment }
     *     
     */
    public Payment getPayment() {
        return payment;
    }

    /**
     * Sets the value of the payment property.
     * 
     * @param value
     *     allowed object is
     *     {@link Payment }
     *     
     */
    public void setPayment(Payment value) {
        this.payment = value;
    }

    /**
     * Gets the value of the alerts property.
     * 
     * @return
     *     possible object is
     *     {@link Alerts }
     *     
     */
    public Alerts getAlerts() {
        return alerts;
    }

    /**
     * Sets the value of the alerts property.
     * 
     * @param value
     *     allowed object is
     *     {@link Alerts }
     *     
     */
    public void setAlerts(Alerts value) {
        this.alerts = value;
    }

    /**
     * Gets the value of the notes property.
     * 
     * @return
     *     possible object is
     *     {@link Notes }
     *     
     */
    public Notes getNotes() {
        return notes;
    }

    /**
     * Sets the value of the notes property.
     * 
     * @param value
     *     allowed object is
     *     {@link Notes }
     *     
     */
    public void setNotes(Notes value) {
        this.notes = value;
    }

    /**
     * Gets the value of the numberOfLines property.
     * 
     * @return
     *     possible object is
     *     {@link Invoice.NumberOfLines }
     *     
     */
    public Invoice.NumberOfLines getNumberOfLines() {
        return numberOfLines;
    }

    /**
     * Sets the value of the numberOfLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link Invoice.NumberOfLines }
     *     
     */
    public void setNumberOfLines(Invoice.NumberOfLines value) {
        this.numberOfLines = value;
    }

    /**
     * Gets the value of the invoiceLine property.
     * 
     * @return
     *     possible object is
     *     {@link InvoiceLine }
     *     
     */
    public List<InvoiceLine> getInvoiceLines() {
        return invoiceLines;
    }

    /**
     * Sets the value of the invoiceLines property.
     * 
     * @param value
     *     allowed object is
     *     {@link InvoiceLines }
     *     
     */
    public void setInvoiceLines(List<InvoiceLine> value) {
        this.invoiceLines = value;
    }
    
    /**
     * adds an InvoiceLine to the invoiceLines property.
     * 
     * @param value
     * 		allowed object is 
     * 		{@link InvoiceLine}
     * 
     */
    public void addInvoiceLine(InvoiceLine value) {
    	invoiceLines.add(value);
    }

    /**
     * Gets the value of the link property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLink() {
        return link;
    }

    /**
     * Sets the value of the link property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLink(String value) {
        this.link = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class CreationForm {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Currency {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceApprovalStatus {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceStatus {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class InvoiceWorkflowStatus {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>int">
     *       &lt;attribute name="link" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class NumberOfLines {

        @XmlValue
        protected int value;
        @XmlAttribute(name = "link")
        protected String link;

        /**
         * Gets the value of the value property.
         * 
         */
        public int getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         */
        public void setValue(int value) {
            this.value = value;
        }

        /**
         * Gets the value of the link property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getLink() {
            return link;
        }

        /**
         * Sets the value of the link property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setLink(String value) {
            this.link = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Owner {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class PaymentMethod {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="desc" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Vendor {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "desc")
        protected String desc;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the desc property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getDesc() {
            return desc;
        }

        /**
         * Sets the value of the desc property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setDesc(String value) {
            this.desc = value;
        }

    }

}
