//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.1-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.11.15 at 09:36:17 AM CET 
//


package libis.invoice.pkg;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the Invoice.pkg package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _InvoiceLine_QNAME = new QName("", "invoice_line");
    private final static QName _Invoice_QNAME = new QName("", "invoice");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: Invoice.pkg
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ExplicitRatios }
     * 
     */
    public ExplicitRatios createExplicitRatios() {
        return new ExplicitRatios();
    }

    /**
     * Create an instance of {@link InvoiceLine.TertiaryReportingCode }
     * 
     */
    public InvoiceLine.TertiaryReportingCode createInvoiceLineTertiaryReportingCode() {
        return new InvoiceLine.TertiaryReportingCode();
    }

    /**
     * Create an instance of {@link FundDistribution }
     * 
     */
    public FundDistribution createFundDistribution() {
        return new FundDistribution();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceApprovalStatus }
     * 
     */
    public Invoice.InvoiceApprovalStatus createInvoiceInvoiceApprovalStatus() {
        return new Invoice.InvoiceApprovalStatus();
    }

    /**
     * Create an instance of {@link InvoiceVat }
     * 
     */
    public InvoiceVat createInvoiceVat() {
        return new InvoiceVat();
    }

    /**
     * Create an instance of {@link InvoiceLine.Type }
     * 
     */
    public InvoiceLine.Type createInvoiceLineType() {
        return new InvoiceLine.Type();
    }

    /**
     * Create an instance of {@link Note }
     * 
     */
    public Note createNote() {
        return new Note();
    }

    /**
     * Create an instance of {@link Invoice.PaymentMethod }
     * 
     */
    public Invoice.PaymentMethod createInvoicePaymentMethod() {
        return new Invoice.PaymentMethod();
    }

    /**
     * Create an instance of {@link Invoice.Currency }
     * 
     */
    public Invoice.Currency createInvoiceCurrency() {
        return new Invoice.Currency();
    }

    /**
     * Create an instance of {@link Notes }
     * 
     */
    public Notes createNotes() {
        return new Notes();
    }

    /**
     * Create an instance of {@link Alerts }
     * 
     */
    public Alerts createAlerts() {
        return new Alerts();
    }

    /**
     * Create an instance of {@link InvoiceVat.VatCode }
     * 
     */
    public InvoiceVat.VatCode createInvoiceVatVatCode() {
        return new InvoiceVat.VatCode();
    }

    /**
     * Create an instance of {@link Payment.PaymentStatus }
     * 
     */
    public Payment.PaymentStatus createPaymentPaymentStatus() {
        return new Payment.PaymentStatus();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceStatus }
     * 
     */
    public Invoice.InvoiceStatus createInvoiceInvoiceStatus() {
        return new Invoice.InvoiceStatus();
    }

    /**
     * Create an instance of {@link InvoiceLineVat }
     * 
     */
    public InvoiceLineVat createInvoiceLineVat() {
        return new InvoiceLineVat();
    }

    /**
     * Create an instance of {@link Invoice.Owner }
     * 
     */
    public Invoice.Owner createInvoiceOwner() {
        return new Invoice.Owner();
    }

    /**
     * Create an instance of {@link InvoiceVat.Type }
     * 
     */
    public InvoiceVat.Type createInvoiceVatType() {
        return new InvoiceVat.Type();
    }

    /**
     * Create an instance of {@link Invoice.InvoiceWorkflowStatus }
     * 
     */
    public Invoice.InvoiceWorkflowStatus createInvoiceInvoiceWorkflowStatus() {
        return new Invoice.InvoiceWorkflowStatus();
    }

    /**
     * Create an instance of {@link InvoiceLine.Status }
     * 
     */
    public InvoiceLine.Status createInvoiceLineStatus() {
        return new InvoiceLine.Status();
    }

    /**
     * Create an instance of {@link ExplicitRatio }
     * 
     */
    public ExplicitRatio createExplicitRatio() {
        return new ExplicitRatio();
    }

    /**
     * Create an instance of {@link InvoiceLine.ReportingCode }
     * 
     */
    public InvoiceLine.ReportingCode createInvoiceLineReportingCode() {
        return new InvoiceLine.ReportingCode();
    }

    /**
     * Create an instance of {@link Invoice }
     * 
     */
    public Invoice createInvoice() {
        return new Invoice();
    }

    /**
     * Create an instance of {@link AdditionalCharges }
     * 
     */
    public AdditionalCharges createAdditionalCharges() {
        return new AdditionalCharges();
    }

    /**
     * Create an instance of {@link Invoice.CreationForm }
     * 
     */
    public Invoice.CreationForm createInvoiceCreationForm() {
        return new Invoice.CreationForm();
    }

    /**
     * Create an instance of {@link Invoice.NumberOfLines }
     * 
     */
    public Invoice.NumberOfLines createInvoiceNumberOfLines() {
        return new Invoice.NumberOfLines();
    }

    /**
     * Create an instance of {@link FundDistribution.FundCode }
     * 
     */
    public FundDistribution.FundCode createFundDistributionFundCode() {
        return new FundDistribution.FundCode();
    }

    /**
     * Create an instance of {@link InvoiceLine.SecondaryReportingCode }
     * 
     */
    public InvoiceLine.SecondaryReportingCode createInvoiceLineSecondaryReportingCode() {
        return new InvoiceLine.SecondaryReportingCode();
    }

    /**
     * Create an instance of {@link Alerts.Alert }
     * 
     */
    public Alerts.Alert createAlertsAlert() {
        return new Alerts.Alert();
    }

    /**
     * Create an instance of {@link ContactPerson }
     * 
     */
    public ContactPerson createContactPerson() {
        return new ContactPerson();
    }

    /**
     * Create an instance of {@link InvoiceLine }
     * 
     */
    public InvoiceLine createInvoiceLine() {
        return new InvoiceLine();
    }

    /**
     * Create an instance of {@link InvoiceLineVat.VatCode }
     * 
     */
    public InvoiceLineVat.VatCode createInvoiceLineVatVatCode() {
        return new InvoiceLineVat.VatCode();
    }

    /**
     * Create an instance of {@link Invoice.Vendor }
     * 
     */
    public Invoice.Vendor createInvoiceVendor() {
        return new Invoice.Vendor();
    }

    /**
     * Create an instance of {@link Payment }
     * 
     */
    public Payment createPayment() {
        return new Payment();
    }

    /**
     * Create an instance of {@link Payment.VoucherCurrency }
     * 
     */
    public Payment.VoucherCurrency createPaymentVoucherCurrency() {
        return new Payment.VoucherCurrency();
    }

    /**
     * Create an instance of {@link FundDistributions }
     * 
     */
    public FundDistributions createFundDistributions() {
        return new FundDistributions();
    }

    /**
     * Create an instance of {@link ExplicitRatio.ForeignCurrency }
     * 
     */
    public ExplicitRatio.ForeignCurrency createExplicitRatioForeignCurrency() {
        return new ExplicitRatio.ForeignCurrency();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvoiceLine }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "invoice_line")
    public JAXBElement<InvoiceLine> createInvoiceLine(InvoiceLine value) {
        return new JAXBElement<InvoiceLine>(_InvoiceLine_QNAME, InvoiceLine.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Invoice }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "invoice")
    public JAXBElement<Invoice> createInvoice(Invoice value) {
        return new JAXBElement<Invoice>(_Invoice_QNAME, Invoice.class, null, value);
    }

}
